wazimap_za/profiles/census.py
wazimap_za/profiles/elections.py
wazimap_za/templates/profile/profile_detail_census.html

Elections profile

---

wazimap_za/static/js/maps_mapit.js
wazimap_za/templates/data/data_map.html

@xybrnet 
Depends on https://github.com/Code4SA/wazimap/pull/13

Use mapit to load geometries for comparison views.

---

requirements.txt
wazimap_za/static/js/maps_mapit.js
wazimap_za/static/js/profile_map_mapit.js
wazimap_za/templates/homepage.html
wazimap_za/templates/profile/profile_detail.html
wazimap_za/templates/profile/profile_detail_census.html
wazimap_za/templates/profile/profile_detail_ecd.html
wazimap_za/templates/profile/profile_detail_youth.html

This re-adds a mapit-based map to the homepage, using the latest release of wazimap.
@xybrnet

Homepage map

---

Procfile

Add newrelic-admin to Procfile

---

Procfile
requirements.txt
wazimap_za/profiles/census.py
wazimap_za/profiles/elections.py
wazimap_za/wsgi.py

Fix static embeds, age groups, registered voters

---

wazimap_za/apps.py
wazimap_za/settings.py
wazimap_za/templates/homepage_ecd.html

Override default homepage template

---

sql/youth_gender_population_group.sql
wazimap_za/profiles/youth.py
wazimap_za/settings.py
wazimap_za/tables.py
wazimap_za/templates/profile/profile_detail_youth.html

Youth population

---

wazimap_za/settings.py
wazimap_za/templates/_base.html
wazimap_za/templates/footer_youth.html
wazimap_za/templates/homepage.html
wazimap_za/templates/homepage_youth.html

Update name and some branding

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Living environment

---

wazimap_za/profiles/youth.py
wazimap_za/tables.py

Education edits

---

sql/youth_population.sql
wazimap_za/profiles/youth.py
wazimap_za/tables.py

Percentage youth

---

wazimap_za/templates/homepage.html

I'm not sure if there's a better way to do this.
@longhotsummer

Add wazimap_za stylesheet to homepage

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Education copy tweaks

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Poverty charts

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Youth unemployment rate by definition

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Layout changes

---

sql/youth_education_attendance_gender_age_incompleted_years.sql
wazimap_za/profiles/youth.py
wazimap_za/tables.py

Use new educational attendance data + rename table

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Some restructuring in here, so that the ordering of the sections in the code match that on the page.

Fix percentages

---

wazimap_za/profiles/youth.py
wazimap_za/tables.py
wazimap_za/templates/profile/profile_detail_youth.html

Living environment changes

---

wazimap_za/static/css/youth.css
wazimap_za/templates/footer_youth.html
wazimap_za/templates/homepage_youth.html
wazimap_za/templates/profile/profile_detail_youth.html

Misc changes

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Profile page tweaks

---

sql/youth_age_16_to_17_gender_completed_grade9.sql
wazimap_za/profiles/youth.py

Update youth completed grade 9 value keys: Completed; Not completed

---

wazimap_za/profiles/youth.py

This is not very nice.
@longhotsummer

Crude fix for geos without informal dwelling types

---

wazimap_za/profiles/youth.py
wazimap_za/templates/footer_youth.html
wazimap_za/templates/profile/profile_detail_youth.html

Layout tweaks

---

wazimap_za/profiles/youth.py

Key order for donut charts

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

More layout changes

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Add difficulty seeing stat number

---

wazimap_za/templates/footer_youth.html
wazimap_za/templates/profile/profile_detail_youth.html

Crime data references

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Youth MPI labels

---

sql/youth_difficulty_functioning.sql
wazimap_za/profiles/youth.py

Change seeing and hearing key names in table

---

sql/youth_dwelling_type.sql
sql/youth_electricity_access.sql
sql/youth_household_crowded.sql
sql/youth_toilet_access.sql
sql/youth_water_access.sql

I have updated the production database with these values.

Zero values

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

Multi field charts

---

wazimap_za/profiles/youth.py
wazimap_za/templates/profile/profile_detail_youth.html

@longhotsummer
This branch was created off the previous pull-request.

Crime rates per 10000

---

wazimap_za/templates/footer_youth.html
wazimap_za/templates/homepage_youth.html

Homepage text

---

wazimap_za/profiles/youth.py
wazimap_za/settings.py
wazimap_za/templates/profile/profile_detail_youth.html

Fix settings

---

wazimap_za/profiles/youth.py
wazimap_za/settings.py
wazimap_za/templates/profile/profile_detail_youth.html

Reverts Code4SA/wazimap-za#100

Revert "Fix settings"

---

bin/README.md
wazimap_za/profiles/youth.py
wazimap_za/tables.py
wazimap_za/templates/profile/profile_detail_youth.html

This branch was based of the branch in the previous pull request.

Youth victims

---

wazimap_za/profiles/youth.py
wazimap_za/tables.py
wazimap_za/templates/profile/profile_detail_youth.html

Youth accused

---

wazimap_za/templates/profile/profile_detail_youth.html

Display rates, not percentages

---

sql/youth_causes_of_death_female.sql
sql/youth_causes_of_death_male.sql
wazimap_za/profiles/youth.py
wazimap_za/tables.py
wazimap_za/templates/profile/profile_detail_youth.html

Causes of death

---

wazimap_za/static/js/profile_maps_youth.js
wazimap_za/templates/homepage.html
wazimap_za/templates/homepage_youth.html

@xybrnet 
It's specific to Youth Explorer, but it works.

Focus youth map on Western Cape

---

wazimap_za/static/css/youth.css
wazimap_za/templates/homepage_youth.html
wazimap_za/templates/homepage_youth_place_finder.html

Homepage edits

---

wazimap_za/templates/_base.html

I find it weird that the previous code didn't work as I thought it would. Anyway.

Fix Wazimap favicon

---

wazimap_za/tables.py

We still need to figure out how to clear the typeahead cache.

Table definitions specifc to profile instance

---

wazimap_za/settings.py

The base wazimap doesn't pull settings from the env, so i've moved that here.

Legacy embed geo version is 2011

---

wazimap_za/geo.py
wazimap_za/settings.py

@xybrnet please can you verify this using Emily's test URL:
http://localhost:8000/data/map/?table=YOUTH_LABOUR_FORCE_OFFICIAL_AGE_GROUP_GENDER&geo_ids=ward-79800037,municipality-JHB,province-GT,country-ZA,ward%7Cmunicipality-JHB&primary_geo_id=ward-79800037#column%7Cunemployed%2Csumlev%7Cward
My databases aren't up to date.

FIX: map view generation

---

wazimap_za/settings.py

@xybrnet this should help ward pages work, defaulting to using 2011 data. Be sure to `git pull` on wazimap's `releases` branch.

Set primary release year

---

wazimap_za/profiles/youth.py

Different key order for some tables

---

wazimap_za/templates/profile/profile_detail_census.html

Needs the evaluative `==` instead of the declarative `=`. :)

Fix if statement in profile detail census
